service: code-explorer-api

provider:
  name: aws
  runtime: nodejs10.x

  stage: dev
  region: eu-west-2

functions:
  request-transfer:
    handler: functions/request-transfer.handler
    events:
      - http:
          path: /request-transfer
          method: get
    environment:
      twilio_sid: ${ssm:/cdex/prod/twilio_sid~true}
      twilio_auth_token: ${ssm:/cdex/prod/twilio_auth_token~true}
      twilio_phone: ${ssm:/cdex/prod/twilio_phone~true}
      admin_phone: ${ssm:/cdex/prod/admin_phone~true}

  payment:
    handler: functions/payment.handler
    events:
      - http:
          path: /payment
          method: get

  fcc-get-completed:
    handler: functions/fcc-get-completed.handler
    events:
      - http:
          path: /fcc-get-completed
          method: get

plugins:
  - serverless-export-env

resources:
  Resources:
    membersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: members
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
