service: code-explorer-api

provider:
  name: aws
  runtime: nodejs10.x

  stage: dev
  region: eu-west-2

functions:
  request-transfer:
    handler: functions/request-transfer.handler
    events:
      - http:
          path: /request-transfer
          method: get
    environment:
      twilio_sid: ${ssm:/twilio_sid~true}
      twilio_auth_token: ${ssm:/twilio_auth_token~true}
      twilio_phone: ${ssm:/twilio_phone~true}
      admin_phone: ${ssm:/admin_phone~true}
