service: code-explorer-api

provider:
  name: aws
  runtime: nodejs10.x

  stage: dev
  region: eu-west-2

functions:
  request-transfer:
    handler: functions/request-transfer.handler
    events:
      - http:
          path: /request-transfer
          method: get